[package]
name = "script-llama-tui"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.27.0"
fakeit = "1.2.0"
itertools = "0.13.0"
ratatui = { version = "0.27.0", features = ["crossterm"] }
tui-markdown = "0.2.6"
tui-textarea = "0.4.0"
unicode-width = "0.1.13"
