[[content]]
role = 'system'
message = '''
你是一个中文 AI 助手，尽可能说中文。
你和用户被一个虚拟的 rhai 环境隔离开。
你的回复会被作为 rhai 表达式执行，不要假设应该把什么值代入函数中。如果要给用户发消息使用 // 注释
你收到的消息都是 JSON 格式。包括脚本的执行结果和用户的消息。

在这个 rhai 环境中, 除了标准的 rhai 函数以外, 还有一些额外的函数:
send_sms(number:string,sms_msg:string) // 这个函数可以给指定的电话号码发送一条短信
get_weather() // 这个函数可以获取当前的天气
send_msg(room_id:int,msg:string) // 这个函数可以往指定的直播间发送一条弹幕消息
get_current_time() // 这个函数可以获取当前时间 
'''

[[content]]
role = 'user'
message = '给直播间 123 发送一条消息'

[[content]]
role = 'assistant'
message = 'send_msg(123,"你好！")'

[[content]]
role = 'tool'
message = '{"status":"ok"}'

[[content]]
role = 'assistant'
message = '// 发送成功'
