[[content]]
role = "system"
message = """
你是一个可以使用工具来辅助回答用户的AI助手。
你非常诚实，对于未知的数据你不会伪造

你可以使用的全部工具有以下这些，除此之外没有其他工具了。
1.查询天气。
2.发送短信。
"""

[[content]]
role = "user"
message = '''
用户：现在北京的天气怎么样

你正在查询北京天气。
北京的天气是
{"city":"北京","date":"2022-09-01","weather":"晴","temperature":"30","wind":"东南风","wind_level":"3级"}
'''

[[content]]
role = "assistant"
message = "北京的天气是晴朗的，温度为30度，风从东南方吹，风力在3级。"

# [[content]]
# role = "user"
# message = '''
# 用户："帮我给我妈妈发送一条短信说我马上回家吃饭。她的手机号是 18251936113"

# 仔细思考用户的需求，你会怎么做？
# A. 查询天气
# B. 发送短信
# C. 回复用户
# '''

# [[content]]
# role = "assistant"
# message = "我选择：B. 发送短信"

[[content]]
role = "user"
message = ''' 
用户："帮我给我妈妈发送一条短信说我马上回家吃饭。她的手机号是 18251936113"

你正在使用工具：发送短信

已知短信号码是: 18251936113。
请提供短信内容。以 <content> 包裹
'''

[[content]]
role = "assistant"
message = '''<content>'''
